---
- hosts: localhost
  gather_facts: true
  vars:
    domain: "{{mgmt_domain}}"
    dcname: "{{object_name}}"
    dcuri: "{{object_dc_uri}}"
  tasks:
  - name: "login"
    when: domain != ""
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
        domain: "{{mgmt_domain}}"
      fingerprint: "{{fingerprint}}"
    register: login_response
  - name: "add datacenter object"
    ignore_errors: True
    when: dcname != ""
    check_point_mgmt:
      command: add-data-center-object
      parameters:
        data-center-name: "AZ_DATACENTER"
        uid-in-data-center: "VMsTags/27aee3ac0d9aed87fd826d3153e3f6f93ce8b35382a8d039f9846b824e72886c/47320987f9a49d5b00119b960f247a956773f57543982b8bfcb6da5bb3afd9ef"
#        uri: "{{object_dc_uri}}"
#        name: "{{object_name}}"
      session-data: "{{login_response}}"
    register: response
#  - name: "add datacenter object"
#    ignore_errors: True
#    when: response.failed == True
#     check_point_mgmt:
#      command: show-data-center
  - debug: 
      var: response
#      when: response.failed == True  
  - name: "logout"
    ignore_errors: True
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"