---
- hosts: localhost
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{fingerprint}}"
    register: login_response
  - name: "add test host"
    check_point_mgmt:
      command: add-host
      parameters:
        name: "test-1234abc"
        ip-address: "1.2.3.4"
        color: "red"
        #domain: "{{mgmt_domain}}"
      session-data: "{{login_response}}"
  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"
  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"