---
- hosts: localhost
  gather_facts: true
  vars:
    domain: "{{mgmt_domain}}"
  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
        domain: "{{mgmt_domain}}"
      fingerprint: "{{fingerprint}}"
    register: login_response
  - name: "show host"
    ignore_errors: True
    check_point_mgmt:
      command: show-host
      parameters:
        name: "{{object_name}}"
      session-data: "{{login_response}}"
    register: response
  - debug: 
      var: response
      when: response.failed == True  
  - name: "logout"
    check_point_mgmt:
      command: logout
      session-data: "{{login_response}}"
